---
title: "California Oil Spills"
author: "Bri Baker"
date: "2/18/2021"
output:
  html_document:
    theme: cosmo
    code_folding: hide
    highlight: kate
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)

library(tidyverse)
library(here)
library(janitor)
library(tmap)
library(sf)

```

## Summary


```{r data}

# read in CA oil spill data
ca_oil <- read_sf(here("part1_spatial/Oil_Spill_Incident_Tracking"), layer = "Oil_Spill_Incident_Tracking") %>% 
  clean_names()

st_crs(ca_oil)

# Read in the CA county data (TIGER shapefile):
ca_counties <- read_sf(here("part1_spatial/ca_counties"), layer = "CA_Counties_TIGER2016") %>% 
  clean_names() %>% 
  select(name)

st_crs(ca_counties)

```


## Interactive Map

```{r interactive}

tmap_mode("view") # interactive mode

tm_shape(ca_oil)+
  tm_dots()

```
Figure 1. 2008 California oil spill locations.

## Inland oil spill events

```{r inland}
inland_spill <- ca_oil %>%
  filter(inlandmari == "Inland")

spill_county <- ca_counties %>% 
  st_join(inland_spill) %>% 
  count(name)

```

```{r}
ggplot(data = spill_county) +
  geom_sf(aes(fill = n), color = "white", size = 0.1) +
  scale_fill_gradientn(colors = c("lightgray","orange","red")) +
  theme_minimal() +
  labs(fill = "Count of oil spills",
       title = "Figure 2. WORDS",
       caption = "Bri Baker, 2021 \nData: SOURCE") +
  theme(legend.position = c(0.75, 0.8), # move legend
        legend.background = element_rect(fill="white", 
                                         linetype = "solid", color = "whitesmoke"))
```




## Citation
https://map.dfg.ca.gov/metadata/ds0394.html
